# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RFUniverseGRPC.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14RFUniverseGRPC.proto\x12\x0eRFUniverseGrpc\"\x07\n\x05\x45mpty\"\x1d\n\rBinaryMessage\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32\xed\x01\n\x15RFUniverseGrpcService\x12\x34\n\x04Link\x12\x15.RFUniverseGrpc.Empty\x1a\x15.RFUniverseGrpc.Empty\x12N\n\x14\x43SharpToPythonStream\x12\x1d.RFUniverseGrpc.BinaryMessage\x1a\x15.RFUniverseGrpc.Empty(\x01\x12N\n\x14PythonToCSharpStream\x12\x15.RFUniverseGrpc.Empty\x1a\x1d.RFUniverseGrpc.BinaryMessage0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RFUniverseGRPC_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=40
  _globals['_EMPTY']._serialized_end=47
  _globals['_BINARYMESSAGE']._serialized_start=49
  _globals['_BINARYMESSAGE']._serialized_end=78
  _globals['_RFUNIVERSEGRPCSERVICE']._serialized_start=81
  _globals['_RFUNIVERSEGRPCSERVICE']._serialized_end=318
# @@protoc_insertion_point(module_scope)
